version: "3.9"

services:
  backend:
    build: ../backend
    container_name: lmstudio_backend
    ports:
      - "${API_PORT:-8001}:8001"
    volumes:
      - dbdata:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      - lmnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ../frontend
    container_name: lmstudio_frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://${HOST_IP:-192.168.4.41}:${API_PORT:-8001}/api
    ports:
      - "${WEB_PORT:-5173}:80"
    networks:
      - lmnet
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  dbdata:

networks:
  lmnet:
    driver: bridge


